### ISSUE TITLE
Fix carousel animation

### ISSUE THREAD

**Issue by staydecent** [inputlogic/elements#23]
This commit that fixed load jank, affects the slide animation as it no longer shows the slides adjacent to each other. Instead, the current slide disappears and the next slide animates in.

https://github.com/inputlogic/elements/pull/20/files#diff-0befc0e52f4dc7d9371d9a09ca136c37L20

cc @coryschadt

**Comment by coryschadt** [comment]
One option would be to add back the transition all, but then set a height on the .carousel container. 
![demo](https://user-images.githubusercontent.com/682876/53825797-02d2ef80-3f2c-11e9-91c5-b983fb89f2ea.gif)

**Comment by staydecent** [comment]
Nice, I wonder if we can auto compute the height 🤔 

Probably would need to support variable height slides, as well?

**Comment by staydecent** [comment]
@coryschadt I believe you may have fixed this?

**Comment by coryschadt** [comment]
Yes, I think things are smooth now.

**Comment by staydecent** [comment]
This should be fixed by https://github.com/inputlogic/elements/pull/20
