### ISSUE TITLE
Pre-made Form Inputs

### ISSUE THREAD

**Issue by staydecent** [inputlogic/elements#24]
What form inputs should be included by default?

This could be text input with some default styling? Or perhaps some specific inputs like Phone Number, Address, with some validation?

Also, default styled select, checkbox, radio?

And, a SubmitButton that automatically shows loading/submitting state.

Anything else? @coryschadt @adriaanwm

**Comment by staydecent** [comment]
- [x] ErrorOrHint
- [x] SubmitButton

**Comment by coryschadt** [comment]
As per out chat, bare min/zero default styling for basic inputs seems like a fair play. I am happy to style each input as needed on a per project basis. Here are some baseline examples: https://codepen.io/coryschadt/pen/KEWbBE

**Comment by staydecent** [comment]
Closed by c5a8b37cd3bff94f6fc40f8e066002762612a3ce
