### ISSUE TITLE
ListResource `endpoint` should be able to be a string or a function.

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#27]
The function is passed the props/state and should return the endpoint. much like withRequest

Example Usage:
If you have a table with a filter input, the table results are based on query string `search` in the url.

**Comment by staydecent** [comment]
Interesting, in my usage I've always had it where the Table component had access to necessary state and the FilterInput and ListResource were children. So the Table would be like:

```
const Table = ({ filter }) =>
  <table>
    <FilterInput />
    <ListResource endpoint={`some-resource?${qs.stringify(filter)}`}
  </table>
```

etc. Definitely open to it tho.
