### ISSUE TITLE
WithState should just accept a function

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#28]
I don't see a need for an object with `mapper` key and then the function. The mapper is the only argument for `withState`

**Comment by staydecent** [comment]
Hmm it includes a way to pass name to the component: https://github.com/inputlogic/elements/blob/master/components/with-state/index.js#L4

But it could check for object or function as the only param.

```
const withState = (optsOrMapper) => PassedComponent => {
  let name
  let mapper
  if (W.toType(optsOrMapper) === 'function') {
    mapper = optsOrMapper
  } else {
    mapper = optsOrMapper.mapper
    name = optsOrMapper.name
  }
```
