### ISSUE TITLE
WithRequest should have a name option

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#29]
If you provide a name then the result should be passed along with a name.

**Comment by staydecent** [comment]
Do you mean something other than the name for the component?

https://github.com/inputlogic/elements/blob/master/components/with-request/index.js#L49

**Comment by adriaanwm** [comment]
I mean if I want the result of the request to be passed along as a named prop like

```
compose(
  withRequest({endpoint: ({search}) => `/users?search=${search}`}, name: 'users'}),
  withRequest({endpoint: ({search}) => `/posts?search=${search}`}, name: 'posts'})
)(({users, posts}) => 
    <div>
        {(!users || !posts) && <Loading />}
        {(users && !users.length && posts && !posts.length) && <Empty />}
        {(users && users.length && users.map(u => <div>{u.name}</div>)}
        {(posts && posts.length && posts.map(p => <div>{p.name}</div>)}
    </div>
)
```

**Comment by staydecent** [comment]
Hmm, I don't think this is the responsibility of `withRequest`, rather I think it falls on `compose` to manage the props it's passing down.

```javascript
compose(
  scoped('users')(withRequest({endpoint: ({search}) => `/users?search=${search}`}),
  scoped('posts')(withRequest({endpoint: ({search}) => `/posts?search=${search}`})
)(({ users: { result: usersResult }, posts { result: postsResult } }))
```

This way you can compose any HoC you want outside of just `withRequest` and ensure the props don't collide.

Some existing work: 
- https://github.com/codevcode/recompose-scope
- https://github.com/Jephuff/namespace-hoc
