### ISSUE TITLE
Why pass a name in to withState?

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#34]
What is the benefit of passing a name in to withState? Can we just change it to only accept a function as its only argument which is the mapper.
If we really need a name associated with the component can we not have a `named()` hoc that could be used along with any hoc?

```
compose(
   named('MyFancyComponent'),
   withState(({token}) => ({isAuthed: !!token}))
)
```

Also the main reason I'm bringing this up is because it looks like `withState` in connect expects just the function, while `withState` as hoc can be an object with `mapper` and `name` and it has caused confusion.

**Comment by staydecent** [comment]
See Higher order Component naming: https://github.com/inputlogic/styleguides/blob/master/react.md#naming

connect also accepts a name. This is at the recommendation of the React docs: https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging

Each HoC offers a means to name the passed/wrapped component.

Connect passes the provided name down to each component, so it's built upon in the same order that the components are in the tree.

Let me know if I can clarify anything.
