### ISSUE TITLE
WithState should update when props are updated.

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#35]
https://github.com/inputlogic/elements/blob/master/components/with-state/index.js#L34-L45

This does not currently work because 
```
W.pipe(
    withState(...),
    withRequest(...)
)()
```

**Comment by staydecent** [comment]
Just to better understand the use-case: 

1. When would a stateful component receive changing prop values over time? Best to have a test written to cover the use case, but I've never written this from what I can recall.
2. Shouldn't we be using `W.compose` for right-to-left composition? Or, even, `connect`?

**Comment by adriaanwm** [comment]
1.
So this compose will work with `withState` before `withRequest`, but not the other way around because `withState` stops `withRequest` props from causing rerender.
```
const Questionnaire = W.compose(
    withState({mapper: state => ({currentQuestionIndex: state.currentQuestionIndex})}),
    withRequest({endpoint: '/questions'})}),
)(({result, currentQuestionIndex}) => 
  <div>
    {result && <Question {...result.results[currentQuestionIndex]} />}
  </div>
)
```

2. 
I didn't realize wasmuth had `compose` but definitely do prefer that. I'm not sure connect is worth the abstraction of just using `compose` anymore 🤷‍♂️

**Comment by staydecent** [comment]
Ahh gotcha. Makes sense about compose. I'll see if I can get the connect test suite to pass just using compose.

**Comment by adriaanwm** [comment]
@staydecent this is also an issue with `withRequest` . When we are updating the `currentQuestionIndex` the updated value doesn't get passed along because withRequest is not updating.

**Comment by staydecent** [comment]
Crazy, is in neighbors I never relied on this pattern 🤔
