### ISSUE TITLE
[Dropdown] - Dropdown won't close when nested link is clicked

### ISSUE THREAD

**Issue by coryschadt** [inputlogic/elements#44]
This bug happens on StepUp. Just tested on PWA starter and it is there as well. 

@staydecent If you have a chance, can you take a look?

![example](https://user-images.githubusercontent.com/682876/56334900-22764e00-614f-11e9-9257-289e65893540.gif)

**Comment by staydecent** [comment]
Should it close if you click an anchor? Or anchor and button? Are there any times when you would click one of those and want the dropdown to stay open?

**Comment by coryschadt** [comment]
Probably both? (anchor and button)

Off the top, I can't think of any times when it should stay open.

**Comment by staydecent** [comment]
Fixed by a989debb39336d2a2f0db8b2e8e2912ad407b5e7

@app-elements/dropdown@2.0.8
