### ISSUE TITLE
Store URI fragment in currentRoute

### ISSUE THREAD

**Issue by weslord** [inputlogic/elements#55]
Useful for storing subnavigational information about a page, such as what tab or view mode is currently active.

For example, a page with two ways of displaying the same information could have `/some-resource/3209#list` or `/some-resource/3209#grid` depending on what mode the user is in. Nice to have for sending links, or just for keeping your place when refreshing a page.

It would make sense to be able to access this in `currentRoute` alongside the other URI-derived information like path and query that's already in there.

**Comment by staydecent** [comment]
@weslord Not sure I understand. `currentRoute` contains values obtained from your route definition:

```javascript
{
  home: {
    path: '/',
    component: Home
  },
  users: {
    path: '/users',
    component: Users
  },
  user: {
    path: '/users/:id',
    component: User
  },
}
```

`currentPath` is the pathname synced via browser `popstate` event. Are you hoping to store more URI information when this `popstate` event is fired? Is the goal to sync the current window.location values to state for consistency?

**Comment by weslord** [comment]
> Are you hoping to store more URI information when this popstate event is fired? Is the goal to sync the current window.location values to state for consistency?

Yes. `currentPath` might be a better place to store this information.

**Comment by weslord** [comment]
I was looking at `currentRoute` as a possible appropriate place for this information because I've used `currentRoute` to access (non-routing) query string data, and found that to be a very useful shortcut in the past.

**Comment by staydecent** [comment]
Hmm, I don't think this makes sense. Are you hoping for stateful re-renders based on changing has h links? I'm also not sure what you mean by "non-routing" query string data? querystrings are parsed and passed as args into `currentRoute`. If you want unique links for different view of the same data, you can use querystrings:

<img width="300" alt="Screen Shot 2019-10-15 at 2 43 53 PM" src="https://user-images.githubusercontent.com/153041/66872300-82ad4780-ef5a-11e9-9b42-b2d0445a43cb.png">

You could also define your routes as: `listing/:id/grid` and `listing/:id/list` etc.

For sending links, I would recommend grabbing the fully qualified URL from the `window.location` object.
