### ISSUE TITLE
Multiple modals?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [inputlogic/elements#64]
Is there any plan for supporting showing multiple modals? For my purposes, I need to have modals opened over other modals, but the example code implies that isn't possible

**Comment by staydecent** [comment]
Hey @vpzomtrrfrt apologies for the slow reply. There is no way to set the global `modal` key in the store to more than just one string.

If you wish to show modals in succession you can trigger the next modal, explicitly, when interacting with the first modal. For example, the first modal could have a "Next" button that when clicked: `dispatch(set('modal', 'NextModal'))`
