### ISSUE TITLE
useActions documentation example is the same as useMappedState

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/elements#66]
I'm guessing the useActions docs are wrong, or do these both do exactly the same thing? @staydecent

**Comment by staydecent** [comment]
Yeah looks wrong, this is actual usage: https://github.com/inputlogic/elements/blob/09ebca2d5f0d9a9de59959906f8159bd94f9a9ce/components/modal/index.js#L17

🙏

**Comment by adriaanwm** [comment]
@staydecent oh weird, is withActions there currying the functions that are passed in? How is `onContainerClick` passed directly to the div `onClick` when it expects `(state, event)` as args?

**Comment by staydecent** [comment]
Yeah, exactly: https://github.com/inputlogic/elements/blob/master/components/connect/index.js#L19

So when you define a function it's actually wrapped by an internal function that will always apply `state` as the first arg, and then spread whatever other args it actually got called with.
